easy_admin:
    site_name: 'Japan80'
    entities:
        # List the entity class name you want to manage
        Article:
          class : App\Entity\Article
          form:
            fields:
              - {property: 'artiste', type_options: { disabled: true }}
              - {property: 'statut', type: 'choice', type_options: {choices: {'En cours' : 'En cours', 'Publié' : 'Publié'}}}
              - {property: 'description', type: 'textarea'}
              - { property: 'cardFile', type: 'vich_image'}
              - { property: 'imageFile', type: 'vich_image'}
              - 'banner_playlist'
          list:
            fields:
              - 'artiste'
              - 'statut'
              - 'dateDerniereModification'
        Album:
          class : App\Entity\Album
          list:
            fields:
              - 'titre'
              - 'artiste'
              - 'type'
              - 'date_sortie'
          form:
            fields:
              - 'titre'
              - 'artiste'
              - 'type'
              - 'date_sortie'
              - { property: 'imageFile', type: 'vich_image'}
        Artiste:
          class : App\Entity\Artiste
          list:
            fields:
              - 'nom'
              - 'nom_jp'
          form:
            fields:
              - 'nom'
              - 'nom_jp'
              - 'nom_alternatif'
              - { property: 'imageFile', type: 'vich_image'}
              - 'genre'
              - { property: 'date_de_naissance', type_options: {widget: 'single_text'}}
              - 'lieu_naissance'
              - 'date_debut'
              - 'date_fin'
              - {property: 'courte_description', type: 'textarea'}
              - 'groupes'
              - 'animes'
        Groupe:
          class: App\Entity\Groupe
          list:
            fields:
              - 'nom'
              - 'nom_jp'
          form:
            fields:
              - 'nom'
              - 'nom_jp'
              - 'date_debut'
              - 'date_fin'
              - 'artistes'
              - { property: 'imageFile', type: 'vich_image'}
        GroupeMembre:
          class: App\Entity\GroupeMembre
        Anime:
          class : App\Entity\Anime
          form:
            fields:
              - 'nom'
              - 'nom_jp'
              - 'nb_episodes'
              - 'nom_romaji'
              - 'realisateur'
              - 'studio'
              - 'genres'
              - { property: 'date_debut', type_options: {widget: 'single_text'}}
              - { property: 'date_fin', type_options: {widget: 'single_text'}}
              - 'artistes'
              - 'courte_description'
              - { property: 'imageFile', type: 'vich_image'}
        AnimeGenre:
          class : App\Entity\AnimeGenre