easy_admin:
    site_name: 'Japan80'
    entities:
        # List the entity class name you want to manage
        Article:
          class : App\Entity\Article
        Album:
          class : App\Entity\Album
        Artiste:
          class : App\Entity\Artiste
          form:
            fields:
              - 'nom'
              - 'nom_jp'
              - 'genre'
              - { property: 'date_de_naissance', type_options: {widget: 'single_text'}}
              - 'lieu_naissance'
              - 'date_debut'
              - 'date_fin'
              - 'courte_description'
              - 'favori'