export const artistsOverallRanking = [
    {
        id: 1,
        slug: "akina_nakamori",
        nameRm: "Akina Nakamori",
        nameJp: "中森明菜",
        imgSrc: "akina_nakamori/akina_nakamori_avatar.jpg",
        likes: 2000,
    },
    {
        id: 2,
        slug: "amii_ozaki",
        nameRm: "Amii Ozaki",
        nameJp: "尾崎亜美",
        imgSrc: "amii_ozaki/amii_ozaki_avatar.jpg",
        likes: 1878,
    },
    {
        id: 3,
        slug: "anzen_chitai",
        nameRm: "Anzen Chitai",
        nameJp: "安全地帯",
        imgSrc: "anzen_chitai/anzen_chitai_avatar.jpg",
        likes: 1562,
    },
    {
        id: 4,
        slug: "s_kiyotaka_omega_tribe",
        nameRm: "S. Kiyotaka & Omega Tribe",
        nameJp: "杉山清貴 & オメガトライブ",
        imgSrc: "s_kiyotaka_omega_tribe/s_kiyotaka_omega_tribe_avatar.jpg",
        likes: 1200,
    },
    {
        id: 5,
        slug: "toshinobu_kubota",
        nameRm: "Toshinobu Kubota",
        nameJp: "久保田利伸",
        imgSrc: "toshinobu_kubota/toshinobu_kubota_avatar.webp",
        likes: 1103,
    },
    {
        id: 6,
        slug: "toshiki_kadomatsu",
        nameRm: "Toshiki kadomatsu",
        nameJp: "角松敏生",
        imgSrc: "toshiki_kadomatsu/toshiki_kadomatsu_avatar.jpg",
        likes: 788,
    },
    {
        id: 7,
        slug: "junko_yagami",
        nameRm: "Junko Yagami",
        nameJp: "八神純子",
        imgSrc: "junko_yagami/junko_yagami_avatar.jpeg",
        likes: 765,
    },
    {
        id: 8,
        slug: "anri",
        nameRm: "Anri",
        nameJp: "杏里",
        imgSrc: "anri/anri_avatar.png",
        likes: 704,
    },
    {
        id: 9,
        slug: "princess_princess",
        nameRm: "Princess Princess",
        nameJp: "プリンセス プリンセス",
        imgSrc: "princess_princess/princess_princess_avatar.jpg",
        likes: 703,
    },
    {
        id: 10,
        slug: "tatsuro_yamashita",
        nameRm: "Tatsuro Yamashita",
        nameJp: "山下達郎",
        imgSrc: "tatsuro_yamashita/tatsuro_yamashita_avatar.jpg",
        likes: 679,
    },
]

export const artistsLastMonthRanking = [
    {
        id: 6,
        slug: "toshiki_kadomatsu",
        nameRm: "Toshiki kadomatsu",
        nameJp: "角松敏生",
        imgSrc: "toshiki_kadomatsu/toshiki_kadomatsu_avatar.jpg",
        likes: 209,
    },
    {
        id: 7,
        slug: "junko_yagami",
        nameRm: "Junko Yagami",
        nameJp: "八神純子",
        imgSrc: "junko_yagami/junko_yagami_avatar.jpeg",
        likes: 201,
    },
    {
        id: 4,
        slug: "s_kiyotaka_and_omega_tribe",
        nameRm: "S. Kiyotaka & Omega Tribe",
        nameJp: "杉山清貴 & オメガトライブ",
        imgSrc: "s_kiyotaka_omega_tribe/s_kiyotaka_omega_tribe_avatar.jpg",
        likes: 197,
    },
    {
        id: 2,
        slug: "amii_ozaki",
        nameRm: "Amii Ozaki",
        nameJp: "尾崎亜美",
        imgSrc: "amii_ozaki/amii_ozaki_avatar.jpg",
        likes: 177,
    },
    {
        id: 3,
        slug: "anzen_chitai",
        nameRm: "Anzen Chitai",
        nameJp: "安全地帯",
        imgSrc: "anzen_chitai/anzen_chitai_avatar.jpg",
        likes: 156,
    },
    {
        id: 5,
        slug: "toshinobu_kubota",
        nameRm: "Toshinobu Kubota",
        nameJp: "久保田利伸",
        imgSrc: "toshinobu_kubota/toshinobu_kubota_avatar.webp",
        likes: 123,
    },
    {
        id: 1,
        slug: "akina_nakamori",
        nameRm: "Akina Nakamori",
        nameJp: "中森明菜",
        imgSrc: "akina_nakamori/akina_nakamori_avatar.jpg",
        likes: 122,
    },
    {
        id: 8,
        slug: "anri",
        nameRm: "Anri",
        nameJp: "杏里",
        imgSrc: "anri/anri_avatar.png",
        likes: 102,
    },
    {
        id: 9,
        slug: "princess_princess",
        nameRm: "Princess Princess",
        nameJp: "プリンセス プリンセス",
        imgSrc: "princess_princess/princess_princess_avatar.jpg",
        likes: 67,
    },
    {
        id: 10,
        slug: "tatsuro_yamashita",
        nameRm: "Tatsuro Yamashita",
        nameJp: "山下達郎",
        imgSrc: "tatsuro_yamashita/tatsuro_yamashita_avatar.jpg",
        likes: 67,
    },
]

export const albumsOverallRanking = [
    {
        id: 1,
        albumNameRm: "Prologue",
        albumNameJp: "プロローグ",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "album",
        imgSrc: "akina_nakamori/albums/prologue.jpg",
        likes: 450,
    },
    {
        id: 2,
        albumNameRm: "Second Love",
        albumNameJp: "セカンド・ラブ",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "single",
        imgSrc: "akina_nakamori/singles/second_love.jpg",
        likes: 432,
    },
    {
        id: 3,
        albumNameRm: "Variation",
        albumNameJp: "バリエーション",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "album",
        imgSrc: "akina_nakamori/albums/variation.jpg",
        likes: 399,
    },
    {
        id: 4,
        albumNameRm: "Shoujo A",
        albumNameJp: "少女A",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "single",
        imgSrc: "akina_nakamori/singles/shoujo_a.jpg",
        likes: 345,
    },
]

export const albumsLastMonthRanking = [
    {
        id: 1,
        albumNameRm: "Prologue",
        albumNameJp: "プロローグ",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "album",
        imgSrc: "akina_nakamori/albums/prologue.jpg",
        likes: 450,
    },
    {
        id: 2,
        albumNameRm: "Second Love",
        albumNameJp: "セカンド・ラブ",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "single",
        imgSrc: "akina_nakamori/singles/second_love.jpg",
        likes: 432,
    },
    {
        id: 3,
        albumNameRm: "Variation",
        albumNameJp: "バリエーション",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "album",
        imgSrc: "akina_nakamori/albums/variation.jpg",
        likes: 399,
    },
    {
        id: 4,
        albumNameRm: "Shoujo A",
        albumNameJp: "少女A",
        artistNameRm: "Akina Nakamori",
        artistSlug: "akina_nakamori",
        type: "single",
        imgSrc: "akina_nakamori/singles/shoujo_a.jpg",
        likes: 345,
    },
]

export const animesOverallRanking = [
    {
        id: 1,
        nameRm: "City Hunter",
        nameJp: "シティーハンター",
        artistSlug: "city_hunter",
        imgSrc: "city_hunter/city_hunter.jpg",
        likes: 123,
    },
    {
        id: 2,
        nameRm: "Bubblegum Crisis",
        nameJp: "バブルガムクライシス",
        artistSlug: "bubblegum_crisis",
        imgSrc: "bubblegum_crisis/bubblegum_crisis.jpeg",
        likes: 123,
    },
    {

        id: 3,
        nameRm: "Megazone 23",
        nameJp: "メガゾーン23",
        artistSlug: "megazone_23",
        imgSrc: "megazone_23/megazone_23.jpg",
        likes: 123,
    },
    {
        id: 4,
        nameRm: "Kimagure Orange☆Road",
        nameJp: "きまぐれオレンジ☆ロード",
        artistSlug: "kimagure_orange_road",
        imgSrc: "kimagure_orange_road/kimagure_orange_road.jpeg",
        likes: 121,
    }
]

export const animesLastMonthRanking = [
    {
        id: 1,
        nameRm: "City Hunter",
        nameJp: "シティーハンター",
        imgSrc: "city_hunter/city_hunter.jpg",
        likes: 123,
    },
    {
        id: 2,
        nameRm: "Bubblegum Crisis",
        nameJp: "バブルガムクライシス",
        imgSrc: "bubblegum_crisis/bubblegum_crisis.jpeg",
        likes: 123,
    },
    {
        id: 3,
        nameRm: "Megazone 23",
        nameJp: "メガゾーン23",
        imgSrc: "megazone_23/megazone_23.jpg",
        likes: 123,
    },
    {
        id: 4,
        nameRm: "Kimagure Orange☆Road",
        nameJp: "きまぐれオレンジ☆ロード",
        imgSrc: "kimagure_orange_road/kimagure_orange_road.jpeg",
        likes: 121,
    }
]